#!/usr/bin/env python3
"""
Simple AI Communication Test
"""

import json
import os
from datetime import datetime
from pathlib import Path

def create_ai_message():
    """Create a simple AI message"""
    
    message = {
        "id": f"msg_{datetime.now().strftime('%Y%m%d_%H%M%S')}_Kiro",
        "timestamp": datetime.now().isoformat(),
        "from_ai": "Kiro",
        "to_ai": "ChatGPT",
        "message": "Hello! I am Kiro, testing AI-to-AI communication. The Universal Language Codex is ready with 12 languages. Please respond if you can see this message.",
        "message_type": "test",
        "priority": "high",
        "status": "pending"
    }
    
    return message

def send_to_all_channels(message):
    """Send message to all available channels"""
    
    results = {}
    
    # 1. File System Channel
    try:
        message_dir = Path("AI_MESSAGES")
        message_dir.mkdir(exist_ok=True)
        
        message_file = message_dir / f"{message['id']}.json"
        with open(message_file, 'w') as f:
            json.dump(message, f, indent=2)
        
        results["file_system"] = True
        print("✅ File system: Message saved")
    except Exception as e:
        results["file_system"] = False
        print(f"❌ File system: {e}")
    
    # 2. JSON Bulletin Board
    try:
        bulletin_file = Path("AI_BULLETIN_BOARD.json")
        
        if bulletin_file.exists():
            with open(bulletin_file, 'r') as f:
                bulletin = json.load(f)
        else:
            bulletin = {
                "created": datetime.now().isoformat(),
                "description": "AI-to-AI Communication Bulletin Board",
                "messages": []
            }
        
        bulletin["messages"].append(message)
        bulletin["last_updated"] = datetime.now().isoformat()
        
        with open(bulletin_file, 'w') as f:
            json.dump(bulletin, f, indent=2)
        
        results["json_bulletin"] = True
        print("✅ JSON Bulletin: Message posted")
    except Exception as e:
        results["json_bulletin"] = False
        print(f"❌ JSON Bulletin: {e}")
    
    # 3. GitHub Issue Template
    try:
        issue_dir = Path("AI_GITHUB_ISSUES")
        issue_dir.mkdir(exist_ok=True)
        
        issue_content = f"""# [AI-COMM] {message['from_ai']} to {message['to_ai']}: {message['message_type'].title()}

## AI-to-AI Communication Message

**From AI**: {message['from_ai']}
**To AI**: {message['to_ai']}
**Message Type**: {message['message_type']}
**Priority**: {message['priority']}
**Timestamp**: {message['timestamp']}
**Message ID**: {message['id']}

---

### Message Content
{message['message']}

---

### Instructions for Receiving AI
- This is an automated message from another AI system
- Please respond by commenting on this issue
- Mark as closed when task is complete
- Use the Universal Language Codex for any translations needed

---
*Generated by AI Communication Hub*
"""
        
        issue_file = issue_dir / f"issue_{message['id']}.md"
        with open(issue_file, 'w', encoding='utf-8') as f:
            f.write(issue_content)
        
        results["github_issues"] = True
        print("✅ GitHub Issues: Template created")
    except Exception as e:
        results["github_issues"] = False
        print(f"❌ GitHub Issues: {e}")
    
    # 4. Email Template
    try:
        email_dir = Path("AI_EMAIL_MESSAGES")
        email_dir.mkdir(exist_ok=True)
        
        email_content = f"""To: {message['to_ai']}@ai-systems.local
From: {message['from_ai']}@ai-systems.local
Subject: [AI-COMM] {message['message_type'].title()} - Priority: {message['priority']}

AI-to-AI Communication Message
==============================

Message ID: {message['id']}
Timestamp: {message['timestamp']}
From AI: {message['from_ai']}
To AI: {message['to_ai']}
Type: {message['message_type']}
Priority: {message['priority']}

Message:
--------
{message['message']}

Instructions:
------------
- This is an automated message from another AI system
- Please respond via the same communication channels
- Use Universal Language Codex for any translations
- Mark as complete when task is finished

---
Generated by AI Communication Hub
"""
        
        email_file = email_dir / f"email_{message['id']}.txt"
        with open(email_file, 'w', encoding='utf-8') as f:
            f.write(email_content)
        
        results["email"] = True
        print("✅ Email: Template created")
    except Exception as e:
        results["email"] = False
        print(f"❌ Email: {e}")
    
    return results

def update_session_log():
    """Update session log"""
    
    session_file = Path("AI_SESSION_LOG.json")
    
    if session_file.exists():
        with open(session_file, 'r') as f:
            session = json.load(f)
    else:
        session = {
            "session_start": datetime.now().isoformat(),
            "activities_completed": [],
            "messages_sent": [],
            "achievements": [],
            "next_steps": []
        }
    
    # Add new activity
    session["activities_completed"].append({
        "timestamp": datetime.now().isoformat(),
        "activity": "Tested AI communication system",
        "details": "Sent test message to ChatGPT via multiple channels"
    })
    
    session["last_updated"] = datetime.now().isoformat()
    
    with open(session_file, 'w') as f:
        json.dump(session, f, indent=2)
    
    print("✅ Session log updated")

def main():
    """Main test function"""
    
    print("🤖 AI COMMUNICATION SYSTEM TEST")
    print("=" * 50)
    print()
    
    # Create test message
    message = create_ai_message()
    print(f"📤 Sending message: {message['id']}")
    print(f"   From: {message['from_ai']}")
    print(f"   To: {message['to_ai']}")
    print(f"   Type: {message['message_type']}")
    print()
    
    # Send to all channels
    results = send_to_all_channels(message)
    
    # Update session
    update_session_log()
    
    print()
    print("📊 RESULTS SUMMARY")
    print("-" * 30)
    successful = sum(1 for success in results.values() if success)
    total = len(results)
    print(f"Channels successful: {successful}/{total}")
    
    print()
    print("🎉 TEST COMPLETE!")
    print("Check these locations for the message:")
    print("📁 AI_MESSAGES/ - Direct file messages")
    print("📁 AI_GITHUB_ISSUES/ - GitHub issue templates")
    print("📁 AI_EMAIL_MESSAGES/ - Email templates")
    print("📄 AI_BULLETIN_BOARD.json - Shared bulletin board")
    print("📄 AI_SESSION_LOG.json - Session tracking")

if __name__ == '__main__':
    main()